package com.kgc.entity;

import java.util.Date;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.empNo
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private Integer empno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.empName
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.birthday
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.deptNo
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private Integer deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.sex
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private String sex;
    private Dept dept;

    public Dept getDept() {
        return dept;
    }

    public void setDept(Dept dept) {
        this.dept = dept;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.sal
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private Double sal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.picPath
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    private String picpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.empNo
     *
     * @return the value of emp.empNo
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.empNo
     *
     * @param empno the value for emp.empNo
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.empName
     *
     * @return the value of emp.empName
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.empName
     *
     * @param empname the value for emp.empName
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.birthday
     *
     * @return the value of emp.birthday
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.birthday
     *
     * @param birthday the value for emp.birthday
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.deptNo
     *
     * @return the value of emp.deptNo
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.deptNo
     *
     * @param deptno the value for emp.deptNo
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.sex
     *
     * @return the value of emp.sex
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.sex
     *
     * @param sex the value for emp.sex
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.sal
     *
     * @return the value of emp.sal
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public Double getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.sal
     *
     * @param sal the value for emp.sal
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setSal(Double sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.picPath
     *
     * @return the value of emp.picPath
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.picPath
     *
     * @param picpath the value for emp.picPath
     *
     * @mbggenerated Wed Jun 12 19:57:34 GMT+08:00 2019
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }


}